name: Build CLI Binaries

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tag like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Nuitka and Python dependencies
        run: |
          pip install -U nuitka
        shell: bash

      # OS-specific compiler setup
      - name: Install compilers (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++

      - name: Build CLI Binary
        run: |
          nuitka cli/main.py --standalone --onefile --output-filename cli_tool
        shell: bash

      - name: Rename Binary by OS
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            mv cli_tool.exe cli_tool-${{ runner.os }}.exe
          else
            mv cli_tool cli_tool-${{ runner.os }}
          fi
        shell: bash

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cli_tool-*
