name: CI - Lint, Type Check, Test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  qa:
    name: Run QA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}t
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run Ruff
        run: ruff check .

      - name: Run Mypy
        run: mypy package/ tests/

      - name: Run Tests
        run: pytest
