name: Release - Version Bump & Tag

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release - Bump Version, Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set Git identity
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Install tools
        run: pip install commitizen

      - name: Run cz bump
        id: bump
        run: |
          cz bump --yes --check-consistency --changelog --files-only
          VERSION=$(cz version --project)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        continue-on-error: false

      - name: Create bump branch, commit and push
        env:
          VERSION: ${{ steps.bump.outputs.version }}
        run: |
          BRANCH="bump/v${VERSION}"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "chore(release): bump version to v${VERSION}"
          git push origin "$BRANCH"

      - name: Setup GitHub CLI
        run: sudo apt install -y gh

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.bump.outputs.version }}
        run: |
          gh pr create \
            --title "chore(release): v${VERSION}" \
            --body "Automated version bump and changelog for v${VERSION}" \
            --base main \
            --head "bump/v${VERSION}" \
            --label release
